//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargedPayRecord
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public Nullable<decimal> AmountPayed { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<System.DateTime> TransactionTime { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
