//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Products = new HashSet<Product>();
        }


        #region private fields
        private string _barcode;
        private string _name;
        private decimal _sellingPrice;
        private string _department;
        private string _details;
        private byte[] _sampleImage;
        private string _type;
        private Nullable<int> _criticalQuantity;
        private bool _isSerialRequired;
        private string _tags;
        #endregion

        #region Public Properties
        public string Id { get; set; }

        [Required(ErrorMessage = "Field Must Be Unique and Not Empty!")]
        public string Name
        {
            get => _name;
            set
            {
                //Console.WriteLine(value);
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged();
                }
            }
        }
        public decimal SellingPrice
        {
            get => _sellingPrice;
            set { if (_sellingPrice != value) { _sellingPrice = value; OnPropertyChanged(); } }
        }

        public string Department
        {
            get => _department;
            set { if (_department != value) { _department = value; OnPropertyChanged(); } }
        }

        public string Details
        {
            get => _details;
            set { if (_details != value) { _details = value; OnPropertyChanged(); } }
        }

        public byte[] SampleImage
        {
            get => _sampleImage;
            set { if (_sampleImage != value) { _sampleImage = value; OnPropertyChanged(); } }
        }

        public string Type
        {
            get => _type;
            set { if (_type != value) { _type = value; OnPropertyChanged(); } }
        }

        public Nullable<int> CriticalQuantity
        {
            get => _criticalQuantity;
            set
            {
                if (_criticalQuantity != value)
                {
                    _criticalQuantity = value;
                    OnPropertyChanged();
                }
            }
        }

        public string Barcode
        {
            get => _barcode;
            set { if (_barcode != value) { _barcode = value; OnPropertyChanged(); } }
        }

        public bool IsSerialRequired
        {
            get => _isSerialRequired;
            set { if (_isSerialRequired != value) { _isSerialRequired = value; OnPropertyChanged(); } }
        }

        public string Tags
        {
            get => _tags;
            set { if (_tags != value) { _tags = value; OnPropertyChanged(); } }
        }
        #endregion

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
