//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Products = new HashSet<Product>();
        }

        public string Id { get; set; }
        [Required]
        public string Name { get; set; }
        public decimal SellingPrice { get; set; }
        [Required]
        public string Department { get; set; }
        public string Details { get; set; }
        public byte[] SampleImage { get; set; }
        public string Type { get; set; }
        public Nullable<int> CriticalQuantity { get; set; }
        public string Tags { get; set; }
        public bool IsSerialRequired { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Warranty { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
