//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Login()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> CanAddItem { get; set; }
        public Nullable<bool> CanEditItem { get; set; }
        public Nullable<bool> CanDeleteItem { get; set; }
        public Nullable<bool> CanAddProduct { get; set; }
        public Nullable<bool> CanEditProduct { get; set; }
        public Nullable<bool> CanDeleteProduct { get; set; }
        public Nullable<bool> CanAddSupplier { get; set; }
        public Nullable<bool> CanEditSupplier { get; set; }
        public Nullable<bool> CanDeleteSupplier { get; set; }
        public Nullable<bool> CanAddCustomer { get; set; }
        public Nullable<bool> CanStockIn { get; set; }
        public Nullable<bool> CanSellItem { get; set; }
        public Nullable<bool> CanAddUser { get; set; }
        public Nullable<bool> CanDeleteUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
